dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-2GB.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-2GB-avb.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-2GB-tee.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-2GB-avb-tee.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-qa-rescue.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-qa-rescue-tee.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-1GB.atv.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-lionskin-1GB.atv-avb.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-papermulberry-glinux-1GB.dtb
dtb-$(CONFIG_ARCH_RTD139x) += rtd-1395-papermulberry-qa-rescue.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
